name: Build

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Run AnApiOfIceAndFire.Setup
        working-directory: src/AnApiOfIceAndFire.Setup
        run: dotnet run -c Release
      - name: Build AnApiOfIceAndFire
        run: dotnet build src/AnApiOfIceAndFire/AnApiOfIceAndFire.csproj -c Release
      - name: Tests
        run: dotnet test tests/AnApiOfIceAndFire.Tests/AnApiOfIceAndFire.Tests.csproj -c Release --logger GitHubActions
  deploy-job:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: build-job
    runs-on: ubuntu-latest
    steps: 
      - name: Publish
        run: dotnet publish -c Release 
